//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQCommon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=(local),1504;database=HedgeQuant;UID=sa; PWD=\'mozaikutca006\'")]
        public string LocalServerHedgeQuantConnectionString {
            get {
                return ((string)(this["LocalServerHedgeQuantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:o81ehksdym.database.windows.net;Database=HedgeQuant;User ID=HQServer@o" +
            "81ehksdym;Password=H667QServer;Trusted_Connection=False;Encrypt=True;Connection " +
            "Timeout=600;")]
        public string ServerHedgeQuantConnectionString {
            get {
                return ((string)(this["ServerHedgeQuantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\HedgeQuant.sdf;Max Database Size=2047")]
        public string ClientHedgeQuantConnectionString {
            get {
                return ((string)(this["ClientHedgeQuantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/public/OfflineDBFiles/")]
        public string SqOfflineDbFilesUrlPathOnly {
            get {
                return ((string)(this["SqOfflineDbFilesUrlPathOnly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GMT")]
        public string SqOfflineDbFilesUrlTimeZoneID {
            get {
                return ((string)(this["SqOfflineDbFilesUrlTimeZoneID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SqlNTryDefault {
            get {
                return ((int)(this["SqlNTryDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hedgequantserver@hqavm1.cloudapp.com")]
        public string EmailSenderForUsers {
            get {
                return ((string)(this["EmailSenderForUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gyantal@gmail.com")]
        public string EmailAddressGyantal {
            get {
                return ((string)(this["EmailAddressGyantal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("meszaros.robert4@gmail.com")]
        public string EmailAddressRobin {
            get {
                return ((string)(this["EmailAddressRobin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("drcharmat@yahoo.com")]
        public string EmailAddressCharmat {
            get {
                return ((string)(this["EmailAddressCharmat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("drcharmat2@gmail.com")]
        public string EmailAddressCharmat2 {
            get {
                return ((string)(this["EmailAddressCharmat2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jmcharmat@yahoo.com")]
        public string EmailAddressJeanCharmat {
            get {
                return ((string)(this["EmailAddressJeanCharmat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("laszlo.nemeth.hu@gmail.com")]
        public string EmailAddressLNemeth {
            get {
                return ((string)(this["EmailAddressLNemeth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blukucz@gmail.com")]
        public string EmailAddressBLukucz {
            get {
                return ((string)(this["EmailAddressBLukucz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("447787069129")]
        public string SmsNumberGyantalUK {
            get {
                return ((string)(this["SmsNumberGyantalUK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36203491806")]
        public string SmsNumberGyantalHU {
            get {
                return ((string)(this["SmsNumberGyantalHU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("447795347979")]
        public string SmsNumberCharmat {
            get {
                return ((string)(this["SmsNumberCharmat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36203210211")]
        public string SmsNumberLNemeth {
            get {
                return ((string)(this["SmsNumberLNemeth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36705705467")]
        public string SmsNumberBLukucz {
            get {
                return ((string)(this["SmsNumberBLukucz"]));
            }
        }
    }
}
